# Generated by Django 4.1.7 on 2023-02-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('ocupantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('cierre', models.DateTimeField(verbose_name='Cierre')),
                ('apertura', models.DateTimeField(verbose_name='Apertura')),
                ('estrellas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='pmdm.atraccion')),
            ],
        ),
    ]
