# Generated by Django 4.1.7 on 2023-02-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
